### ISSUE TITLE
Error when exporting

### ISSUE THREAD

**Issue by sconoverCRM** [khoait/DynCrmExp.Deduplicator#21]
Greetings.  I keep encountering an issue when exporting the results from deduplicator.  The issue message is attached.  I am curious if someone can provide guidance.  I am unable to interpret the instructions on the prompt.  I have successfully exported many times so not sure what's up.  

Thanks

![dedupe error when exporting 2020-03-17_14-59-13](https://user-images.githubusercontent.com/62311720/76906556-31d7ad00-6872-11ea-9193-a6cd72b06fa2.png)

---
- Deployment: Online
- DB Version: 9.1.0.14143
- XTB Version: 1.2020.2.37
- Tool Version: 1.2020.3.14

**Comment by khoait** [comment]
Hi @sconoverCRM, thanks for using the plugin and giving your feedback. I decided to update CsvHelper to the latest version, looks like it doesn't like it :) I'll fix it soon and let you know.

**Comment by khoait** [comment]
I'll close this as duplicated with #20

**Comment by khoait** [comment]
Hi @sconoverCRM . This is fixed in v1.2020.3.18. Enjoy! :)
