### ISSUE TITLE
System.SeviceModel.Fault exception

### ISSUE THREAD

**Issue by darthenjoys** [khoait/DynCrmExp.Deduplicator#8]
Hello,

When launching the plugin and trying to load the entities I have this message 

![image](https://user-images.githubusercontent.com/45872401/49996297-f4111800-ff8e-11e8-9e4e-d6739fcc1fa4.png)

I'm running Dynamics CRM 2015 on premise BTW

**Comment by JenCambell** [comment]
HI, I'm getting the same error on attempting to load my organisation's entities.  How do you get this to work please?  (We are CRM2013 on prem)
Thanks,
Jennifer

**Comment by darthenjoys** [comment]
Still the same issue after updating the plugin

[cid:image001.png@01D4F5C9.DF0CB2D0]




De : Khoa Nguyen <notifications@github.com>
Envoyé : jeudi 18 avril 2019 08:41
À : khoait/DynCrmExp.Deduplicator <DynCrmExp.Deduplicator@noreply.github.com>
Cc : Steve BOUVIER <s.bouvier@groupevivialys.com>; Author <author@noreply.github.com>
Objet : Re: [khoait/DynCrmExp.Deduplicator] System.SeviceModel.Fault exception (#8)


Closed #8<https://github.com/khoait/DynCrmExp.Deduplicator/issues/8> via #9<https://github.com/khoait/DynCrmExp.Deduplicator/pull/9>.

**Comment by khoait** [comment]
Hi darthejoys,

I haven't updated the plugin yet. Hopefully, I can find some time this weekend.

You can build the source code and replace the current plugin dll with your built dll in XrmToolbox plugins folder.

Thanks for using the plugin!
